const categories = [
  {
    category: "eyeglasses",
    items: [
      "Plastic Frames",
      "Metal Frames",
      "Full Frames",
      "Semi-Rimless Frames",
      "Rimless Frames",
      "Polycarbonate Lenses",
      "Round Frames",
      "Oval Frames",
      "Square Frames",
      "Cat Eye Frames",
      "Aviator Frames",
      "Rectangular Frames",
      "Horn-Rimmed Frames",
      "Wayfarer Frames",
      "Clubmaster Frames",
      "Clip-On Frames",
    ],
  },
  {
    category: "tshirt",
    items: [
      "V-neck tshirts",
      "Basic half sleeve tshirts",
      "Long Sleeve Crew neck tshirts",
      "Pollo collar tshirts",
      "Ringer tshirts",
      "Turtle neck tshirts",
      "Longline tshirts",
      "Pocket tshirts",
      "Douche bag neck tshirts",
      "Henley tshirts",
      "Graphic tshirts",
      "Sleeveless tshirts",
      "Muscle tshirts",
      "Slub tshirts",
      "Thermal tshirts",
      "Raglan tshirts",
    ],
  },
  {
    category: "hoodie",
    items: [
      "Zip-Up hoodies",
      "Pullover hoodies",
      "Fitted hoodies",
      "Athletic hoodies",
      "Knit-hoodies",
      "Designer hoodies",
      "Sleeveless hoodies",
      "Fleece hoodies",
      "Button-Up Cardigan Sweater hoodies",
      "Flannel Button-Up hoodies",
      "Tubic-Style hoodies",
      "Thermal hoodies",
      "High-Neck hoodies",
      "Cropped hoodies",
      "Sherpa hoodies",
      "Quilted hoodies",
    ],
  },
  {
    category: "jeans",
    items: [
      "Skinny Jeans",
      "Straight-leg Jeans",
      "Bootcut Jeans",
      "Flared Jeans",
      "Boyfriend Jeans",
      "High-Waisted Jeans",
      "Low-Rise Jeans",
      "Mom Jeans",
      "Jeggings Jeans",
      "Distressed Jeans",
      "Cropped Jeans",
      "Wide-Leg Jeans",
      "Tapered Jeans",
      "Slim Fit Jeans",
      "Relaxed Fit Jeans",
      "Stretch Jeans",
    ],
  },
  {
    category: "shirt",
    items: [
      "Dress Shirts",
      "Collar Dress Shirts",
      "Tuxedo Dress Shirts",
      "Denim Shirts",
      "Men's Casual Shirts",
      "Button-Down Shirts",
      "Banded Collar Shirts",
      "Spread Collar Shirts",
      "Club Collar Shirts",
      "Flannel Shirts",
      "Oxford Shirts",
      "Chambray Shirts",
      "Linen Shirts",
      "Hawaiian Shirts",
      "Western Shirts",
      "Military Shirts",
    ],
  },
  {
    category: "pants",
    items: [
      "Bell Bottom Pants",
      "Bootcut Pants",
      "Breeches Pants",
      "Cargo Pants",
      "Carpenter Pants",
      "Chaps Pants",
      "Chinos Pants",
      "Corduroy Pants",
      "Dickies Pants",
      "Flat Front Pants",
      "Joggers",
      "Pleated Pants",
      "Suit Pants",
      "Khaki Pants",
      "Track Pants",
      "Trousers",
    ],
  },
];

export default categories;